const fs=require('node:fs'), assert=require('node:assert/strict'), ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);require.extensions['.css']=()=>{};
const storage=new Map();global.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
const THREE=require('three'),{StreetWorld}=require('../src/world.ts'),{schoolClient}=require('../src/schoolFeed.ts');
function fixture(){const car=new THREE.Group(), input={value:'',select(){}},feedback={textContent:''};const w=Object.assign(Object.create(StreetWorld.prototype),{root:{querySelector:s=>s.includes('answer')?input:feedback},car,avatar:new THREE.Group(),onFoot:false,overlay:false,keys:new Set(),touches:new Map(),speed:0,yaw:0,boost:100,blocks:[],legs:[],ramps:[],rivals:[],loot:[],recovered:[],records:[],owned:['Gold GT'],footVelocity:0,streetRewards:[],upgrades:{},stage:'pickup',question:{a:12,b:14},wins:0,mission:0,heat:0,lastSafe:new THREE.Vector3(),jumpCooldown:0,verticalSpeed:0,airborneRamp:-1,landedRamps:[],paidRamps:[],rangeScore:0,streak:0,lastHit:0,fireCooldown:0,parkPass:false,ammo:0,hits:0,spaces:0,estate:new THREE.Group(),scene:new THREE.Scene(),targets:[],currentRide:{mesh:car,name:'Gold GT',max:55,acceleration:32,kind:'car'}});w.rides=[w.currentRide];w.modal=html=>{w.overlay=true;w.html=html};w.closeModal=()=>w.overlay=false;w.notify=()=>{};w.input=input;w.solve=n=>{input.value=String(n);w.answer()};return w;}
let w=fixture();w.vehicle();assert.equal(w.onFoot,true);w.vehicle();assert.equal(w.onFoot,false);
w.car.position.set(460,0,0);w.vehicle();assert.ok(w.land(w.avatar.position.x,w.avatar.position.z),'exit stays on land');
w=fixture();w.onFoot=true;w.keys.add('KeyW');for(let i=0;i<80;i++)w.drive(.02);assert.equal(w.speed,9);w.keys.add('ShiftLeft');for(let i=0;i<40;i++)w.drive(.02);assert.equal(w.speed,16);
w=fixture();w.onFoot=true;const stolen={mesh:new THREE.Group(),name:'Vortex RS',max:85,acceleration:43,kind:'car'};stolen.mesh.position.set(5,0,0);w.car.position.set(50,0,0);w.rides.push(stolen);w.vehicle();w.solve(1);assert.equal(w.onFoot,true);w.solve(168);assert.equal(w.currentRide,stolen);assert.equal(w.owned.includes('Vortex RS'),false);w.answer();assert.equal(w.records.length,2);
w=fixture();w.car.position.set(460,0,0);w.yaw=Math.PI/2;w.speed=55;w.drive(.04);assert.equal(w.car.position.x,460,'shore blocks street vehicles');
w.currentRide.kind='boat';w.car.position.set(550,0,120);w.speed=50;w.drive(.04);assert.ok(w.car.position.x>550,'boat crosses open water');w.car.position.set(630,0,120);w.vehicle();assert.equal(w.onFoot,true);assert.ok(w.land(w.avatar.position.x,w.avatar.position.z));
console.log('PASS walking, sprint, safe exits, hotwire retries, single unlock, shore collision, boat crossing and disembark');
module.exports={fixture,schoolClient,assert,THREE};
